### ISSUE TITLE
[ORDER] The landing order — 4 epics, 15 stories, sequenced for earliest observable signal

### ISSUE THREAD

**Issue by paulgsc** [paulgsc/resume-ui#1314]
Milestone `topik` (#24) carries MOB-TOPIK (#1298) directly; the three general-purpose epics this relay also created — MOB-CITIZEN (#1295), MOB-GESTURE (#1296), MOB-ORIENT (#1297) — live in `www` (#19), since their primitives serve the composer as much as TOPIK. This issue sequences all four together because MOB-TOPIK depends on the other three's primitives; it does not add work, it states the order the four epics' own dependency notes already imply.

## Where this came from

A report against `/sessions/new` on a phone found the composer's pager flashing and landing wrong, the box not growing to fill the screen, and landscape wasting space. That work landed already (branch `claude/mobile-composer-pagination-flicker-hxomtp`, PR #1294): `useFittedPage`'s rewrite, the composer's bounded shell, and `short-window.ts`'s first two class strings. A follow-up report named the idiom this relay is for, verbatim:

> in mobile mode, the idiom is, only one first class citizen occupying the screen at a time, and we want 'thumb' ergonomics for 'press', 'slide (left, right, up, down)', and double tap, and also we want to be aware of landscape vs normal mode and what we want to fit in a viewport.

...and separately, that TOPIK's own mobile session view needs a full redesign, not a fit-pass — mobile-first, orthogonal to the desktop experience, deliberately not landed in one sitting but filed for this relay to pick up (MOB-TOPIK, #1298).

## The sequence

**Step 1 — independent, land in any order or in parallel**
- [ ] CIT1 · #1299 — the demotion ladder, written down. Gates CIT2, CIT3, ORI2, and (indirectly) every MOB-TOPIK story that cites it.
- [ ] GES1 · #1302 — `useThumbGestures`, the primitive. Gates GES2, GES4.
- [ ] GES3 · #1304 — `PageControls`' 44px targets. No dependency on anything.
- [ ] ORI1 · #1306 — `useWindowShape`, the primitive. Gates ORI2, TPK4.
- [ ] TPK2 · #1309 — "Check Answer"'s fixed footer. A real, cheap, isolated bug fix — independent of the citizen/gesture/orientation work entirely.
- [ ] TPK3 · #1310 — `ChatPanel`/`QuizPanel` Storybook stories. Land early so every later TOPIK story has something to check against.

**Step 2 — depends on Step 1**
- [ ] CIT2 · #1300 — needs CIT1. The composer manifest collapses on a short window.
- [ ] CIT3 · #1301 — needs CIT1. `review-step.tsx`'s omissions get cited.
- [ ] GES2 · #1303 — needs GES1. Swipe wired into the composer's pagers.
- [ ] ORI2 · #1307 — needs ORI1 and CIT1 (a real consumer must exist first — see its own "done when").
- [ ] TPK1 · #1308 — needs CIT1 (the ladder it applies to TOPIK's own regions). The design decision the rest of MOB-TOPIK depends on.

**Step 3 — depends on Step 2**
- [ ] GES4 · #1305 — needs CIT2 (the first sheet this repo produces) and GES1.
- [ ] TPK4 · #1311 — needs TPK1 and ORI1. The actual chat/quiz restructure.
- [ ] TPK5 · #1312 — needs TPK1 and CIT1.

**Step 4 — depends on Step 3**
- [ ] TPK6 · #1313 — needs TPK1, TPK4, GES4, and CIT1's sheet primitive. The last TOPIK story, and the one with the most dependencies — land it last on purpose.

## What this issue is not

It does not implement any of the fifteen stories above — each is its own PR. It does not resequence PR #1294, which is a separate, already-in-flight piece of work this relay's groundwork depends on but does not gate on. And it does not decide MOB-TOPIK's design questions itself — TPK1 does that, against CIT1's ladder, not this issue.

## Cross-cutting notes

- **Milestone split is deliberate, not an oversight.** MOB-CITIZEN, MOB-GESTURE, and MOB-ORIENT sit in `www` (#19) because their primitives are consumed by the composer today and by TOPIK once TPK1/TPK4/TPK5/TPK6 land — they are not TOPIK-specific. Only MOB-TOPIK itself sits in `topik` (#24).
- **Every TOPIK story cites a real file and line**, traced against the actual `packages/ui/topik` source rather than inferred — a PR closing one should be checkable against the same citation.
- **A future session picking this up**: read the live state of whichever issue you're closing before trusting this issue's own summary of it — the same rule this repo's `CLAUDE.md` states for multi-session relay work in general.
